#!/usr/bin/env node
/**
 * Scans `src/icons/` and generates `src/generated/`: a manifest
 * module, one module per family re-exporting that family's icons, and
 * a catalog module wiring the two together behind a
 * `FamilyModuleResolver`. See ADR-0019.
 *
 * `src/generated/` is committed, not gitignored: it is plain,
 * readable TypeScript, not a build artifact hidden from review, and
 * it is what lets `src/index.ts` auto-configure itself with zero
 * dynamic-glob machinery, so it must work under plain `tsc`, exactly
 * like every other file in `src/`.
 *
 * Same convention as `FsManifestBuilder` (see ADR-0006, ADR-0015):
 * every direct subdirectory of `iconsDir` is a family, every
 * recognized icon source file directly inside it is one icon, named
 * after the file itself with the extension removed. Not implemented
 * by calling `FsManifestBuilder` itself: this script runs against
 * plain `src/icons/*.ts` files via `node:fs`, before `tsc` has run,
 * so it cannot import that class (or anything else under `src/`)
 * without a TypeScript loader. Deliberately duplicates the small
 * filename-parsing rule instead, kept in sync with
 * `src/shared/iconFileName.ts` by the two scanning tests in
 * `tests/scripts/generateCatalog.test.ts`.
 *
 * Usage: node generate-catalog.mjs [iconsDir] [outDir]
 * Defaults to ./src/icons and ./src/generated relative to cwd.
 *
 * Lives at repo root, not under `scripts/`, deliberately, the same
 * reason `fix-esm-extensions.mjs` does, see ADR-0018: `scripts/` is
 * never synced to the public repo (ADR-0017), but both repos' own
 * `npm run build` needs this file, since `src/generated/` — though
 * committed — is regenerated fresh on every build to guarantee it can
 * never silently drift from `src/icons/`.
 */

import { readdirSync, mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const ICON_SOURCE_EXTENSIONS = new Set(['.ts', '.js']);

/** Mirrors `src/shared/iconFileName.ts`'s `iconNameFromFileName`. */
function iconNameFromFileName(fileName) {
  const dot = fileName.lastIndexOf('.');
  if (dot <= 0) {
    return null;
  }
  const ext = fileName.slice(dot).toLowerCase();
  if (!ICON_SOURCE_EXTENSIONS.has(ext)) {
    return null;
  }
  return fileName.slice(0, dot);
}

/** A valid JS identifier for a given icon/family name, for local import bindings. */
function toIdentifier(name, index) {
  const safe = name.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^[0-9]/, '_$&');
  return `${safe}_${index}`;
}

function scanIcons(iconsDir) {
  const topLevel = readdirSync(iconsDir, { withFileTypes: true });
  const families = topLevel
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  /** @type {Map<string, Array<{ name: string, fileName: string }>>} */
  const byFamily = new Map();

  for (const family of families) {
    const familyDir = path.join(iconsDir, family);
    const iconFiles = readdirSync(familyDir, { withFileTypes: true });
    const icons = [];
    const seen = new Map();

    const fileNames = iconFiles
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name)
      .sort();

    for (const fileName of fileNames) {
      const name = iconNameFromFileName(fileName);
      if (name === null) {
        continue;
      }
      const firstFile = seen.get(name);
      if (firstFile) {
        throw new Error(
          `generate-catalog: duplicate icon id "${family}:${name}", first found in "${firstFile}", second in "${fileName}".`
        );
      }
      seen.set(name, fileName);
      icons.push({ name, fileName });
    }

    if (icons.length > 0) {
      byFamily.set(family, icons);
    }
  }

  return byFamily;
}

function generatedFileHeader() {
  return [
    '/**',
    ' * AUTO-GENERATED by `npm run generate:catalog` (generate-catalog.mjs).',
    ' * Do not edit by hand, see ADR-0019. Re-run the script after adding,',
    ' * renaming, or removing an icon under `src/icons/`.',
    ' */',
    '',
  ].join('\n');
}

function writeFamilyModule(outDir, family, icons) {
  const lines = [generatedFileHeader()];
  const bindings = icons.map((icon, index) => ({ ...icon, binding: toIdentifier(icon.name, index) }));

  for (const { binding, name } of bindings) {
    lines.push(`import ${binding} from '../../icons/${family}/${name}';`);
  }
  lines.push('');
  lines.push('export default {');
  for (const { binding, name } of bindings) {
    lines.push(`  ${JSON.stringify(name)}: ${binding},`);
  }
  lines.push('};');
  lines.push('');

  const filePath = path.join(outDir, 'families', `${family}.ts`);
  writeFileSync(filePath, lines.join('\n'));
  return filePath;
}

function writeManifest(outDir, byFamily) {
  const lines = [generatedFileHeader()];
  lines.push("import { toIconId, type Manifest } from '../core/domain';");
  lines.push('');
  lines.push('export const GENERATED_MANIFEST: Manifest = new Map([');
  for (const [family, icons] of byFamily) {
    for (const { name } of icons) {
      lines.push(`  [toIconId(${JSON.stringify(family)}, ${JSON.stringify(name)}), ${JSON.stringify(family)}],`);
    }
  }
  lines.push(']);');
  lines.push('');

  writeFileSync(path.join(outDir, 'manifest.ts'), lines.join('\n'));
}

function writeCatalog(outDir, byFamily) {
  const families = [...byFamily.keys()].sort();
  const lines = [generatedFileHeader()];
  lines.push("import type { FamilyModuleResolver } from '../core/loader/DynamicImportIconLoader';");
  lines.push('');
  lines.push('const familyLoaders: Record<string, () => Promise<{ default: Record<string, unknown> }>> = {');
  for (const family of families) {
    lines.push(`  ${JSON.stringify(family)}: () => import('./families/${family}'),`);
  }
  lines.push('};');
  lines.push('');
  lines.push('/**');
  lines.push(' * {@link FamilyModuleResolver} backed by the generated per-family');
  lines.push(' * modules above, one static `import()` per family so bundlers can');
  lines.push(' * still code-split, and plain `node` can still resolve it, see');
  lines.push(' * ADR-0019.');
  lines.push(' */');
  lines.push('export const resolveGeneratedFamilyModule: FamilyModuleResolver = async (family) => {');
  lines.push('  const load = familyLoaders[family];');
  lines.push('  if (!load) {');
  lines.push('    throw new Error(`generated catalog: no icons found for family "${family}".`);');
  lines.push('  }');
  lines.push('  return load() as ReturnType<FamilyModuleResolver>;');
  lines.push('};');
  lines.push('');

  writeFileSync(path.join(outDir, 'catalog.ts'), lines.join('\n'));
}

function main() {
  const cwd = process.cwd();
  const iconsDir = path.resolve(cwd, process.argv[2] ?? 'src/icons');
  const outDir = path.resolve(cwd, process.argv[3] ?? 'src/generated');

  if (!existsSync(iconsDir)) {
    console.error(`generate-catalog: ${iconsDir} does not exist.`);
    process.exit(1);
  }

  const byFamily = scanIcons(iconsDir);

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(path.join(outDir, 'families'), { recursive: true });

  let iconCount = 0;
  for (const [family, icons] of byFamily) {
    writeFamilyModule(outDir, family, icons);
    iconCount += icons.length;
  }
  writeManifest(outDir, byFamily);
  writeCatalog(outDir, byFamily);

  console.log(
    `generate-catalog: wrote ${byFamily.size} family module(s), ${iconCount} icon(s) into ${path.relative(cwd, outDir)}`
  );
}

// `import.meta.url` is always a correctly formatted `file://` URL
// (forward slashes, drive letter percent-free on Windows too); naively
// building one from `process.argv[1]` via string concatenation is
// NOT equivalent on Windows, where `process.argv[1]` is a plain path
// with backslashes (`C:\Users\...`) — `file://` + that never equals
// `import.meta.url`, so this guard silently never matched, `main()`
// silently never ran, and the script exited 0 having done nothing.
// `pathToFileURL(...).href` is the one conversion that's correct on
// every platform, POSIX included, see ADR-0019's own note about the
// identical class of bug in the acceptance check.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}

// Exported for tests only (not run as a script when imported).
export { scanIcons, iconNameFromFileName };
